### ISSUE TITLE
undefined symbol: xmlFreeNodeList

### ISSUE THREAD

**Issue by kostya** [serpapi/nokolexbor#1]
```ruby
require "nokolexbor"
doc = Nokolexbor::HTML("")
```

```
/var/lib/gems/3.0.0/gems/nokolexbor-0.2.0/lib/nokolexbor.rb:3:in `require': /var/lib/gems/3.0.0/gems/nokolexbor-0.2.0/lib/nokolexbor/nokolexbor.so: undefined symbol: xmlFreeNodeList - /var/lib/gems/3.0.0/gems/nokolexbor-0.2.0/lib/nokolexbor/nokolexbor.so (LoadError)
        from /var/lib/gems/3.0.0/gems/nokolexbor-0.2.0/lib/nokolexbor.rb:3:in `<top (required)>'
```

**Comment by zyc9012** [comment]
@kostya What is your OS? I tested on Ubuntu 20.04, Ruby 2.7 + Ruby 3.1.2, without problem.

**Comment by zyc9012** [comment]
@kostya Fixed and released new version.

**Comment by kostya** [comment]
still failing:
```
/var/lib/gems/3.0.0/gems/nokolexbor-0.2.1/lib/nokolexbor.rb:3:in `require': /var/lib/gems/3.0.0/gems/nokolexbor-0.2.1/lib/nokolexbor/nokolexbor.so: undefined symbol: strnstr - /var/lib/gems/3.0.0/gems/nokolexbor-0.2.1/lib/nokolexbor/nokolexbor.so (LoadError)
        from /var/lib/gems/3.0.0/gems/nokolexbor-0.2.1/lib/nokolexbor.rb:3:in `<top (required)>'

```

**Comment by zyc9012** [comment]
> still failing:
> 
> ```
> /var/lib/gems/3.0.0/gems/nokolexbor-0.2.1/lib/nokolexbor.rb:3:in `require': /var/lib/gems/3.0.0/gems/nokolexbor-0.2.1/lib/nokolexbor/nokolexbor.so: undefined symbol: strnstr - /var/lib/gems/3.0.0/gems/nokolexbor-0.2.1/lib/nokolexbor/nokolexbor.so (LoadError)
>         from /var/lib/gems/3.0.0/gems/nokolexbor-0.2.1/lib/nokolexbor.rb:3:in `<top (required)>'
> ```

What is your OS and gcc version?

**Comment by kostya** [comment]
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Ubuntu 22.04.1 LTS

**Comment by zyc9012** [comment]
@kostya Can you try this gem locally and see if it fixes the error? 

[nokolexbor-0.2.1.gem.zip](https://github.com/serpapi/nokolexbor/files/10236442/nokolexbor-0.2.1.gem.zip)
```
gem uninstall nokolexbor
gem install /path/to/nokolexbor-0.2.1.gem
```

**Comment by kostya** [comment]
It works if i do gem uninstall && gem install, from rubygems or from your file.
But if i install it from bundler, `undefined symbol: strnstr`

**Comment by zyc9012** [comment]
> It works if i do gem uninstall && gem install, from rubygems or from your file. But if i install it from bundler, `undefined symbol: strnstr`

Just released new version and it should be good now.

**Comment by kostya** [comment]
fixed, thanks.

**Comment by kostya** [comment]
just compare with crystal, funny that in ruby parse faster, that in compiled language.
crystal parse: 2.88s, css: 0.6s
ruby parse: 2.34s, css: 1.43s

**Comment by zyc9012** [comment]
> Probably in crystal finalize, and free memory called on every step. I dont know how it called in ruby.

It will be freed on GC, depending on how large the document is.

I'm wondering why css differs that much.

**Comment by zyc9012** [comment]
> is css not only pure lib time but also extract array. and loop in ruby, which is should be slower.

I'm not using ruby array but lexbor array. Maybe because I did extra things like making result set unique and ordering the result set.
