### ISSUE TITLE
Ship pre-compiled `lexbor` binaries

### ISSUE THREAD

**Issue by ilyazub** [serpapi/nokolexbor#5]
Nokogiri is shipped with the [pre-compiled binaries](https://github.com/sparklemotion/nokogiri/blob/88b3e2feefb51ab79b7586b1147a8b3c2d5abcda/rakelib/extensions.rake#L322-L341). While `lexbor` is compiled pretty fast (< 25 seconds), it can be _even more_ convenient if `cmake` won't be required and gem installation time would be faster.

Here are rake tasks that are used to pre-compile libxml2 in Nokogiri:
https://github.com/sparklemotion/nokogiri/blob/88b3e2feefb51ab79b7586b1147a8b3c2d5abcda/rakelib/extensions.rake#L322-L341

_Thanks for your work, @zyc9012 :+1:_

**Comment by zyc9012** [comment]
Yeah, I have the plan for it, but haven't started to implement and test. A concern of mine was, if shipped with pre-compiled binaries, will we lose the opportunity to optimize for latest CPU features (such as avx256), because we have to target older CPUs?

**Comment by ilyazub** [comment]
Does `lexbor` or `nokolexbor` use SIMD instructions? How different is the Nokolexbor performance when compiled with and without the latest CPU features? 

In any case, we can self-host a CI runners with the modern CPUs to compile lexbor and libxml2. _(Sounds like an over-engineering.)_

**Comment by zyc9012** [comment]
Tried with `-O3 -march=native` but resulted in no difference. 😞

**Comment by zyc9012** [comment]
@ilyazub It's done.

See https://github.com/serpapi/nokolexbor/actions/runs/3810516328 and https://rubygems.org/gems/nokolexbor/versions

**Comment by ilyazub** [comment]
@zyc9012 Thank you!
