### ISSUE TITLE
Fragments return element_children.first but not first_element_child

### ISSUE THREAD

**Issue by jaredcwhite** [serpapi/nokolexbor#7]
It seems that a document fragment will return element children as expected via `element_children`, and then of course you can call `.first`, but calling `first_element_child` will return nil.

**Comment by zyc9012** [comment]
Thanks @jaredcwhite! Fixed by c33b9e13ab09695fa088613ce6583dfe698152a8. If it's not urgent, I will release a new version with more future fixes.

**Comment by jaredcwhite** [comment]
@zyc9012 Certainly not urgent. Thanks!

**Comment by jaredcwhite** [comment]
Working well now!
